# Generated by Django 5.2.13 on 2026-04-30 23:59

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('source_app', models.CharField(max_length=50)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_identifier', models.CharField(blank=True, max_length=128)),
                ('session_identifier', models.CharField(blank=True, max_length=128)),
                ('object_type', models.CharField(blank=True, max_length=64)),
                ('object_key', models.CharField(blank=True, max_length=140)),
                ('properties', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
                'indexes': [models.Index(fields=['source_app', 'name'], name='events_source_name_idx'), models.Index(fields=['actor_identifier', 'occurred_at'], name='events_actor_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('result', models.CharField(choices=[('success', 'Success'), ('warning', 'Warning'), ('failure', 'Failure'), ('info', 'Info')], default='info', max_length=16)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_identifier', models.CharField(blank=True, max_length=128)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_key', models.CharField(blank=True, max_length=140)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
                'indexes': [models.Index(fields=['action', 'result'], name='audit_action_result_idx'), models.Index(fields=['actor_identifier', 'occurred_at'], name='audit_actor_time_idx')],
            },
        ),
    ]
