# Generated by Django 5.2.13 on 2026-05-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='result',
            field=models.CharField(choices=[('success', 'Успешно'), ('warning', 'Предупреждение'), ('failure', 'Ошибка'), ('info', 'Информация')], default='info', max_length=16),
        ),
    ]
