# Generated by Django 5.2.13 on 2026-05-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_russian_ui_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsevent',
            options={'ordering': ('-occurred_at', '-id'), 'verbose_name': 'аналитическое событие', 'verbose_name_plural': 'аналитические события'},
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ('-occurred_at', '-id'), 'verbose_name': 'запись аудита', 'verbose_name_plural': 'записи аудита'},
        ),
    ]
