# Generated by Django 5.2.13 on 2026-05-02 08:42

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_russian_admin_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='actor_identifier',
            field=models.CharField(blank=True, max_length=128, verbose_name='инициатор'),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='object_key',
            field=models.CharField(blank=True, max_length=140, verbose_name='ключ объекта'),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='object_type',
            field=models.CharField(blank=True, max_length=64, verbose_name='тип объекта'),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='произошло'),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='properties',
            field=models.JSONField(blank=True, default=dict, verbose_name='свойства'),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный ID'),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='session_identifier',
            field=models.CharField(blank=True, max_length=128, verbose_name='сессия'),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='source_app',
            field=models.CharField(max_length=50, verbose_name='модуль-источник'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=100, verbose_name='действие'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor_identifier',
            field=models.CharField(blank=True, max_length=128, verbose_name='инициатор'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='message',
            field=models.TextField(blank=True, verbose_name='сообщение'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='произошло'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='данные'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='result',
            field=models.CharField(choices=[('success', 'Успешно'), ('warning', 'Предупреждение'), ('failure', 'Ошибка'), ('info', 'Информация')], default='info', max_length=16, verbose_name='результат'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_key',
            field=models.CharField(blank=True, max_length=140, verbose_name='ключ объекта'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_type',
            field=models.CharField(blank=True, max_length=64, verbose_name='тип объекта'),
        ),
    ]
