# Generated by Django 5.2.13 on 2026-05-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadprofile',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('preview', 'Пробный доступ'), ('registered', 'Зарегистрирован'), ('converted', 'Оплатил'), ('archived', 'В архиве')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='magiclink',
            name='purpose',
            field=models.CharField(choices=[('login', 'Вход'), ('diagnostic_preview', 'Пробный вход из диагностики'), ('payment_access', 'Платный доступ'), ('admin_invite', 'Приглашение администратора')], max_length=32),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('super_admin', 'Супер админ'), ('admin', 'Админ'), ('manager', 'Менеджер'), ('student', 'Ученик'), ('lead', 'Лид'), ('system', 'Система')], max_length=32, unique=True),
        ),
    ]
