# Generated by Django 5.2.13 on 2026-05-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_russian_ui_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'профиль лида', 'verbose_name_plural': 'профили лидов'},
        ),
        migrations.AlterModelOptions(
            name='magiclink',
            options={'ordering': ['-created_at'], 'verbose_name': 'магическая ссылка', 'verbose_name_plural': 'магические ссылки'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['code'], 'verbose_name': 'роль', 'verbose_name_plural': 'роли'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['user_id', 'role__code'], 'verbose_name': 'роль пользователя', 'verbose_name_plural': 'роли пользователей'},
        ),
        migrations.AlterModelOptions(
            name='usertelegramidentity',
            options={'ordering': ['telegram_id'], 'verbose_name': 'Telegram-профиль', 'verbose_name_plural': 'Telegram-профили'},
        ),
    ]
