# Generated by Django 5.2.13 on 2026-05-02 08:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_russian_admin_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadprofile',
            name='consent_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='согласия'),
        ),
        migrations.AlterField(
            model_name='leadprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='leadprofile',
            name='diagnostic_segment',
            field=models.CharField(blank=True, max_length=128, verbose_name='сегмент диагностики'),
        ),
        migrations.AlterField(
            model_name='leadprofile',
            name='diagnostic_session_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='сессия диагностики'),
        ),
        migrations.AlterField(
            model_name='leadprofile',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='метаданные'),
        ),
        migrations.AlterField(
            model_name='leadprofile',
            name='source',
            field=models.CharField(default='diagnostic', max_length=64, verbose_name='источник'),
        ),
        migrations.AlterField(
            model_name='leadprofile',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('preview', 'Пробный доступ'), ('registered', 'Зарегистрирован'), ('converted', 'Оплатил'), ('archived', 'В архиве')], default='new', max_length=32, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='leadprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='leadprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='magiclink',
            name='consumed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='использовано'),
        ),
        migrations.AlterField(
            model_name='magiclink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='magiclink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_magic_links', to=settings.AUTH_USER_MODEL, verbose_name='кто создал'),
        ),
        migrations.AlterField(
            model_name='magiclink',
            name='expires_at',
            field=models.DateTimeField(verbose_name='истекает'),
        ),
        migrations.AlterField(
            model_name='magiclink',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='метаданные'),
        ),
        migrations.AlterField(
            model_name='magiclink',
            name='purpose',
            field=models.CharField(choices=[('login', 'Вход'), ('diagnostic_preview', 'Пробный вход из диагностики'), ('payment_access', 'Платный доступ'), ('admin_invite', 'Приглашение администратора')], max_length=32, verbose_name='назначение'),
        ),
        migrations.AlterField(
            model_name='magiclink',
            name='redirect_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='путь после входа'),
        ),
        migrations.AlterField(
            model_name='magiclink',
            name='token_hash',
            field=models.CharField(max_length=128, unique=True, verbose_name='хэш токена'),
        ),
        migrations.AlterField(
            model_name='magiclink',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='magic_links', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('super_admin', 'Супер админ'), ('admin', 'Админ'), ('manager', 'Менеджер'), ('student', 'Ученик'), ('lead', 'Лид'), ('system', 'Система')], max_length=32, unique=True, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(max_length=120, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='имя на платформе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Europe/Moscow', max_length=64, verbose_name='часовой пояс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='granted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='выдано'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_role_links', to=settings.AUTH_USER_MODEL, verbose_name='кто выдал'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='reason',
            field=models.TextField(blank=True, verbose_name='причина'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_links', to='accounts.role', verbose_name='роль'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='usertelegramidentity',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='usertelegramidentity',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='usertelegramidentity',
            name='linked_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='привязано'),
        ),
        migrations.AlterField(
            model_name='usertelegramidentity',
            name='telegram_id',
            field=models.BigIntegerField(unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='usertelegramidentity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='usertelegramidentity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_identities', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='usertelegramidentity',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='логин Telegram'),
        ),
    ]
