# Generated by Django 5.2.13 on 2026-05-01 00:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('diagnostic_site', 'Diagnostic site'), ('telegram_bot', 'Telegram bot'), ('payment_provider', 'Payment provider'), ('video_hosting', 'Video hosting'), ('manual', 'Manual')], max_length=32)),
                ('event_type', models.CharField(max_length=100)),
                ('idempotency_key', models.CharField(max_length=180, unique=True)),
                ('processing_status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='received', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-received_at', '-id'],
                'indexes': [models.Index(fields=['source', 'event_type'], name='integr_event_source_type_idx'), models.Index(fields=['processing_status', 'received_at'], name='integr_event_status_time_idx')],
            },
        ),
    ]
