# Generated by Django 5.2.13 on 2026-05-01 23:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('notifications', '0002_notificationjob_dedupe_key_dead_letter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationOutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('telegram_bot', 'Telegram bot')], max_length=32)),
                ('event_type', models.CharField(max_length=100)),
                ('idempotency_key', models.CharField(max_length=180, unique=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('dead_letter', 'Dead letter'), ('canceled', 'Canceled')], default='pending', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_outbox_events', to='notifications.notificationjob')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_outbox_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_at', 'id'],
                'indexes': [models.Index(fields=['destination', 'event_type'], name='integr_outbox_dest_type_idx'), models.Index(fields=['processing_status', 'scheduled_at'], name='integr_outbox_status_time_idx')],
            },
        ),
    ]
