# Generated by Django 5.2.13 on 2026-05-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_integrationoutboxevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalevent',
            name='processing_status',
            field=models.CharField(choices=[('received', 'Получено'), ('processed', 'Обработано'), ('failed', 'Ошибка'), ('ignored', 'Проигнорировано')], default='received', max_length=16),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='source',
            field=models.CharField(choices=[('diagnostic_site', 'Сайт диагностики'), ('telegram_bot', 'Telegram-бот'), ('payment_provider', 'Платёжный провайдер'), ('video_hosting', 'Видеохостинг'), ('manual', 'Вручную')], max_length=32),
        ),
        migrations.AlterField(
            model_name='integrationoutboxevent',
            name='destination',
            field=models.CharField(choices=[('telegram_bot', 'Telegram-бот')], max_length=32),
        ),
        migrations.AlterField(
            model_name='integrationoutboxevent',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('dead_letter', 'Не доставлено'), ('canceled', 'Отменено')], default='pending', max_length=16),
        ),
    ]
