# Generated by Django 5.2.13 on 2026-05-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_russian_ui_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalevent',
            options={'ordering': ['-received_at', '-id'], 'verbose_name': 'входящее событие интеграции', 'verbose_name_plural': 'входящие события интеграций'},
        ),
        migrations.AlterModelOptions(
            name='integrationoutboxevent',
            options={'ordering': ['scheduled_at', 'id'], 'verbose_name': 'исходящее событие интеграции', 'verbose_name_plural': 'исходящие события интеграций'},
        ),
    ]
