# Generated by Django 5.2.13 on 2026-05-02 08:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_russian_admin_labels'),
        ('notifications', '0006_russian_admin_field_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalevent',
            name='error',
            field=models.TextField(blank=True, verbose_name='ошибка'),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='event_type',
            field=models.CharField(max_length=100, verbose_name='тип события'),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='idempotency_key',
            field=models.CharField(max_length=180, unique=True, verbose_name='ключ идемпотентности'),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='данные'),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='обработано'),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='processing_status',
            field=models.CharField(choices=[('received', 'Получено'), ('processed', 'Обработано'), ('failed', 'Ошибка'), ('ignored', 'Проигнорировано')], default='received', max_length=16, verbose_name='статус обработки'),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='получено'),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='source',
            field=models.CharField(choices=[('diagnostic_site', 'Сайт диагностики'), ('telegram_bot', 'Telegram-бот'), ('payment_provider', 'Платёжный провайдер'), ('video_hosting', 'Видеохостинг'), ('manual', 'Вручную')], max_length=32, verbose_name='источник'),
        ),
        migrations.AlterField(
            model_name='integrationoutboxevent',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='попытки'),
        ),
        migrations.AlterField(
            model_name='integrationoutboxevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='integrationoutboxevent',
            name='destination',
            field=models.CharField(choices=[('telegram_bot', 'Telegram-бот')], max_length=32, verbose_name='получатель'),
        ),
        migrations.AlterField(
            model_name='integrationoutboxevent',
            name='event_type',
            field=models.CharField(max_length=100, verbose_name='тип события'),
        ),
        migrations.AlterField(
            model_name='integrationoutboxevent',
            name='idempotency_key',
            field=models.CharField(max_length=180, unique=True, verbose_name='ключ идемпотентности'),
        ),
        migrations.AlterField(
            model_name='integrationoutboxevent',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='последняя ошибка'),
        ),
        migrations.AlterField(
            model_name='integrationoutboxevent',
            name='notification_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_outbox_events', to='notifications.notificationjob', verbose_name='уведомление'),
        ),
        migrations.AlterField(
            model_name='integrationoutboxevent',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='данные'),
        ),
        migrations.AlterField(
            model_name='integrationoutboxevent',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('dead_letter', 'Не доставлено'), ('canceled', 'Отменено')], default='pending', max_length=16, verbose_name='статус обработки'),
        ),
        migrations.AlterField(
            model_name='integrationoutboxevent',
            name='scheduled_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='запланировано'),
        ),
        migrations.AlterField(
            model_name='integrationoutboxevent',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='отправлено'),
        ),
        migrations.AlterField(
            model_name='integrationoutboxevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='integrationoutboxevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_outbox_events', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
