# Generated by Django 5.2.13 on 2026-05-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'В архиве')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('article', 'Статья'), ('worksheet', 'Рабочий лист'), ('checklist', 'Чек-лист'), ('template', 'Шаблон'), ('link', 'Ссылка'), ('download', 'Файл')], max_length=24),
        ),
    ]
