# Generated by Django 5.2.13 on 2026-05-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_russian_ui_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('title', 'id'), 'verbose_name': 'материал', 'verbose_name_plural': 'материалы'},
        ),
    ]
