# Generated by Django 5.2.13 on 2026-05-02 08:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_russian_admin_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='download_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='ключ файла'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='метаданные'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный ID'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'В архиве')], default='draft', max_length=16, verbose_name='статус публикации'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('article', 'Статья'), ('worksheet', 'Рабочий лист'), ('checklist', 'Чек-лист'), ('template', 'Шаблон'), ('link', 'Ссылка'), ('download', 'Файл')], max_length=24, verbose_name='тип материала'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='slug',
            field=models.SlugField(max_length=140, unique=True, verbose_name='URL-ярлык'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='теги'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
    ]
