# Generated by Django 5.2.13 on 2026-05-01 00:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('diagnostic_site', 'Diagnostic site'), ('telegram_bot', 'Telegram bot'), ('manual', 'Manual')], default='diagnostic_site', max_length=32)),
                ('external_session_id', models.CharField(max_length=128)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('resolved', 'Resolved'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='created', max_length=16)),
                ('diagnostic_segment', models.CharField(blank=True, max_length=128)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('replay_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_handoffs', to='accounts.leadprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_handoffs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at', '-id'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='diag_handoff_status_exp_idx'), models.Index(fields=['lead_profile', 'status'], name='diag_handoff_lead_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_session_id'), name='diagnostic_handoff_source_session_uniq')],
            },
        ),
    ]
