# Generated by Django 5.2.13 on 2026-05-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_handoff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostichandoff',
            name='source',
            field=models.CharField(choices=[('diagnostic_site', 'Сайт диагностики'), ('telegram_bot', 'Telegram-бот'), ('manual', 'Вручную')], default='diagnostic_site', max_length=32),
        ),
        migrations.AlterField(
            model_name='diagnostichandoff',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('resolved', 'Обработан'), ('expired', 'Истёк'), ('revoked', 'Отозван')], default='created', max_length=16),
        ),
    ]
