# Generated by Django 5.2.13 on 2026-05-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_handoff', '0002_russian_ui_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnostichandoff',
            options={'ordering': ['-submitted_at', '-id'], 'verbose_name': 'передача из диагностики', 'verbose_name_plural': 'передачи из диагностики'},
        ),
    ]
