# Generated by Django 5.2.13 on 2026-05-02 08:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_russian_admin_field_labels'),
        ('diagnostic_handoff', '0003_russian_admin_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostichandoff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='diagnostichandoff',
            name='diagnostic_segment',
            field=models.CharField(blank=True, max_length=128, verbose_name='сегмент диагностики'),
        ),
        migrations.AlterField(
            model_name='diagnostichandoff',
            name='expires_at',
            field=models.DateTimeField(verbose_name='истекает'),
        ),
        migrations.AlterField(
            model_name='diagnostichandoff',
            name='external_session_id',
            field=models.CharField(max_length=128, verbose_name='внешняя сессия'),
        ),
        migrations.AlterField(
            model_name='diagnostichandoff',
            name='idempotency_key',
            field=models.CharField(max_length=160, unique=True, verbose_name='ключ идемпотентности'),
        ),
        migrations.AlterField(
            model_name='diagnostichandoff',
            name='lead_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_handoffs', to='accounts.leadprofile', verbose_name='профиль лида'),
        ),
        migrations.AlterField(
            model_name='diagnostichandoff',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='сырые данные'),
        ),
        migrations.AlterField(
            model_name='diagnostichandoff',
            name='replay_count',
            field=models.PositiveIntegerField(default=0, verbose_name='повторные открытия'),
        ),
        migrations.AlterField(
            model_name='diagnostichandoff',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='обработано'),
        ),
        migrations.AlterField(
            model_name='diagnostichandoff',
            name='source',
            field=models.CharField(choices=[('diagnostic_site', 'Сайт диагностики'), ('telegram_bot', 'Telegram-бот'), ('manual', 'Вручную')], default='diagnostic_site', max_length=32, verbose_name='источник'),
        ),
        migrations.AlterField(
            model_name='diagnostichandoff',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('resolved', 'Обработан'), ('expired', 'Истёк'), ('revoked', 'Отозван')], default='created', max_length=16, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='diagnostichandoff',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='получено'),
        ),
        migrations.AlterField(
            model_name='diagnostichandoff',
            name='token_hash',
            field=models.CharField(max_length=128, unique=True, verbose_name='хэш токена'),
        ),
        migrations.AlterField(
            model_name='diagnostichandoff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='diagnostichandoff',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_handoffs', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
