# Generated by Django 5.2.13 on 2026-04-30 23:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('publication_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('position', models.PositiveIntegerField(default=0)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('position', 'title', 'id'),
                'indexes': [models.Index(fields=['publication_status', 'position'], name='curr_course_state_pos_idx')],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=140)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('publication_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('position', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='curriculum.course')),
            ],
            options={
                'ordering': ('course_id', 'position', 'title', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=140)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('publication_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('position', models.PositiveIntegerField(default=0)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.module')),
            ],
            options={
                'ordering': ('module_id', 'position', 'title', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LessonBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_type', models.CharField(choices=[('rich_text', 'Rich text'), ('video', 'Video'), ('embed', 'Embed'), ('download', 'Download'), ('action', 'Action')], max_length=24)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='curriculum.lesson')),
            ],
            options={
                'ordering': ('lesson_id', 'position', 'id'),
                'indexes': [models.Index(fields=['lesson', 'block_type'], name='curr_block_lesson_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('lesson', 'position'), name='curr_block_lesson_pos_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'publication_status'], name='curr_module_course_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course', 'slug'), name='curr_module_course_slug_uniq'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course', 'position'), name='curr_module_course_pos_uniq'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'publication_status'], name='curr_lesson_module_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('module', 'slug'), name='curr_lesson_module_slug_uniq'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('module', 'position'), name='curr_lesson_module_pos_uniq'),
        ),
    ]
