# Generated by Django 5.2.13 on 2026-05-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'В архиве')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'В архиве')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='block_type',
            field=models.CharField(choices=[('rich_text', 'Текст'), ('video', 'Видео'), ('embed', 'Встраивание'), ('download', 'Файл'), ('action', 'Действие')], max_length=24),
        ),
        migrations.AlterField(
            model_name='module',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'В архиве')], default='draft', max_length=16),
        ),
    ]
