# Generated by Django 5.2.13 on 2026-05-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_russian_ui_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('position', 'title', 'id'), 'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('module_id', 'position', 'title', 'id'), 'verbose_name': 'урок', 'verbose_name_plural': 'уроки'},
        ),
        migrations.AlterModelOptions(
            name='lessonblock',
            options={'ordering': ('lesson_id', 'position', 'id'), 'verbose_name': 'блок урока', 'verbose_name_plural': 'блоки уроков'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('course_id', 'position', 'title', 'id'), 'verbose_name': 'модуль', 'verbose_name_plural': 'модули'},
        ),
    ]
