# Generated by Django 5.2.13 on 2026-05-02 08:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_russian_admin_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='длительность в минутах'),
        ),
        migrations.AlterField(
            model_name='course',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='позиция'),
        ),
        migrations.AlterField(
            model_name='course',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'В архиве')], default='draft', max_length=16, verbose_name='статус публикации'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=140, unique=True, verbose_name='URL-ярлык'),
        ),
        migrations.AlterField(
            model_name='course',
            name='summary',
            field=models.TextField(blank=True, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='длительность в минутах'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.module', verbose_name='модуль'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='позиция'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'В архиве')], default='draft', max_length=16, verbose_name='статус публикации'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(max_length=140, verbose_name='URL-ярлык'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='summary',
            field=models.TextField(blank=True, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='block_type',
            field=models.CharField(choices=[('rich_text', 'Текст'), ('video', 'Видео'), ('embed', 'Встраивание'), ('download', 'Файл'), ('action', 'Действие')], max_length=24, verbose_name='тип блока'),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='body',
            field=models.TextField(blank=True, verbose_name='содержимое'),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='обязательный'),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='curriculum.lesson', verbose_name='урок'),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='данные блока'),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='позиция'),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='curriculum.course', verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='module',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='module',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='позиция'),
        ),
        migrations.AlterField(
            model_name='module',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'В архиве')], default='draft', max_length=16, verbose_name='статус публикации'),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(max_length=140, verbose_name='URL-ярлык'),
        ),
        migrations.AlterField(
            model_name='module',
            name='summary',
            field=models.TextField(blank=True, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='module',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
    ]
