# Generated by Django 5.2.13 on 2026-05-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_state', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressrecord',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('opened', 'Открыто'), ('in_progress', 'В процессе'), ('completed', 'Завершено')], default='not_started', max_length=16),
        ),
    ]
