# Generated by Django 5.2.13 on 2026-05-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_state', '0002_russian_ui_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressrecord',
            options={'ordering': ['user_id', 'course_id', 'module_id', 'lesson_id'], 'verbose_name': 'прогресс обучения', 'verbose_name_plural': 'прогресс обучения'},
        ),
    ]
