# Generated by Django 5.2.13 on 2026-05-02 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_russian_admin_field_labels'),
        ('learning_state', '0003_russian_admin_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressrecord',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='завершено'),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='curriculum.course', verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='first_opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='первое открытие'),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='last_opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='последнее открытие'),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='curriculum.lesson', verbose_name='урок'),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='метаданные'),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='curriculum.module', verbose_name='модуль'),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='source',
            field=models.CharField(blank=True, max_length=64, verbose_name='источник'),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('opened', 'Открыто'), ('in_progress', 'В процессе'), ('completed', 'Завершено')], default='not_started', max_length=16, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
