# Generated by Django 5.2.13 on 2026-05-01 01:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0002_initial'),
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.CharField(max_length=64, unique=True)),
                ('provider_code', models.CharField(choices=[('robokassa', 'Robokassa')], default='robokassa', max_length=32)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='created', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('return_path', models.CharField(max_length=255)),
                ('provider_payment_id', models.CharField(blank=True, max_length=128)),
                ('access_granted_at', models.DateTimeField(blank=True, null=True)),
                ('success_returned_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('disputed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('access_grant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_order', to='access_control.accessgrant')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_orders', to='curriculum.course')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_orders', to='access_control.tariff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_code', models.CharField(choices=[('robokassa', 'Robokassa')], default='robokassa', max_length=32)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='pending', max_length=16)),
                ('dedupe_key', models.CharField(max_length=160)),
                ('provider_event_id', models.CharField(blank=True, max_length=128)),
                ('provider_payment_id', models.CharField(blank=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('signature_status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('skipped', 'Skipped')], default='skipped', max_length=16)),
                ('is_valid', models.BooleanField(default=True)),
                ('invalid_reason', models.TextField(blank=True)),
                ('processing_result', models.CharField(blank=True, max_length=64)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='commerce.order')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='comm_order_user_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['provider_code', 'status'], name='comm_order_provider_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['order', 'status', 'processed_at'], name='comm_event_order_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['provider_code', 'provider_event_id'], name='comm_event_provider_evt_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentevent',
            constraint=models.UniqueConstraint(fields=('order', 'dedupe_key'), name='comm_event_order_dedupe_uniq'),
        ),
    ]
