# Generated by Django 5.2.13 on 2026-05-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('pending', 'Ожидает подтверждения'), ('paid', 'Оплачен'), ('failed', 'Не оплачен'), ('refunded', 'Возвращён'), ('disputed', 'На проверке')], default='created', max_length=16),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='signature_status',
            field=models.CharField(choices=[('valid', 'Проверена'), ('invalid', 'Ошибка подписи'), ('skipped', 'Не проверялась')], default='skipped', max_length=16),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('pending', 'Ожидает подтверждения'), ('paid', 'Оплачен'), ('failed', 'Не оплачен'), ('refunded', 'Возвращён'), ('disputed', 'На проверке')], default='pending', max_length=16),
        ),
    ]
