# Generated by Django 5.2.13 on 2026-05-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_russian_ui_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterModelOptions(
            name='paymentevent',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'платёжное событие', 'verbose_name_plural': 'платёжные события'},
        ),
    ]
