# Generated by Django 5.2.13 on 2026-05-02 08:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0006_russian_admin_field_labels'),
        ('commerce', '0003_russian_admin_labels'),
        ('curriculum', '0004_russian_admin_field_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='access_grant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_order', to='access_control.accessgrant', verbose_name='доступ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='access_granted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='доступ выдан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_orders', to='curriculum.course', verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='RUB', max_length=3, verbose_name='валюта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='спор'),
        ),
        migrations.AlterField(
            model_name='order',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ошибка оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_event_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='последнее событие'),
        ),
        migrations.AlterField(
            model_name='order',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='метаданные'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=64, unique=True, verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='оплачено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider_code',
            field=models.CharField(choices=[('robokassa', 'Robokassa')], default='robokassa', max_length=32, verbose_name='провайдер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider_payment_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='ID платежа у провайдера'),
        ),
        migrations.AlterField(
            model_name='order',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='возвращено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='return_path',
            field=models.CharField(max_length=255, verbose_name='путь возврата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('pending', 'Ожидает подтверждения'), ('paid', 'Оплачен'), ('failed', 'Не оплачен'), ('refunded', 'Возвращён'), ('disputed', 'На проверке')], default='created', max_length=16, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='success_returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='успешный возврат'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_orders', to='access_control.tariff', verbose_name='тариф'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_orders', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='сумма'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='currency',
            field=models.CharField(default='RUB', max_length=3, verbose_name='валюта'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='dedupe_key',
            field=models.CharField(max_length=160, verbose_name='ключ идемпотентности'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='invalid_reason',
            field=models.TextField(blank=True, verbose_name='причина ошибки'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='валидно'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='произошло'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='commerce.order', verbose_name='заказ'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='данные события'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='обработано'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='processing_result',
            field=models.CharField(blank=True, max_length=64, verbose_name='результат обработки'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='provider_code',
            field=models.CharField(choices=[('robokassa', 'Robokassa')], default='robokassa', max_length=32, verbose_name='провайдер'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='provider_event_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='ID события у провайдера'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='provider_payment_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='ID платежа у провайдера'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='signature_status',
            field=models.CharField(choices=[('valid', 'Проверена'), ('invalid', 'Ошибка подписи'), ('skipped', 'Не проверялась')], default='skipped', max_length=16, verbose_name='статус подписи'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('pending', 'Ожидает подтверждения'), ('paid', 'Оплачен'), ('failed', 'Не оплачен'), ('refunded', 'Возвращён'), ('disputed', 'На проверке')], default='pending', max_length=16, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
    ]
