# Generated by Django 5.2.13 on 2026-05-01 00:07

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('starts_after_purchase_minutes', models.PositiveIntegerField(default=0)),
                ('availability_window_hours', models.PositiveIntegerField(default=48)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['tariff_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('preview', 'Preview'), ('payment', 'Payment'), ('manual', 'Manual'), ('import', 'Import')], default='preview', max_length=16)),
                ('status', models.CharField(choices=[('preview', 'Preview'), ('active', 'Active'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('archived', 'Archived')], default='preview', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PreviewAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('consumed', 'Consumed'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-starts_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('workshop', 'Workshop'), ('base', 'Base'), ('mentor', 'Mentor'), ('vip', 'VIP')], max_length=32, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('price_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('access_duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['sort_order', 'price_amount', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TariffEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=160)),
                ('entitlement_type', models.CharField(choices=[('course', 'Course'), ('module', 'Module'), ('lesson', 'Lesson'), ('resource', 'Resource'), ('homework_review', 'Homework review'), ('bonus', 'Bonus'), ('community', 'Community'), ('vip_support', 'VIP support')], max_length=32)),
                ('reference_key', models.CharField(blank=True, max_length=160)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['tariff_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('payment', 'Payment'), ('manual', 'Manual'), ('import', 'Import'), ('upgrade', 'Upgrade')], default='manual', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('frozen', 'Frozen')], default='active', max_length=16)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('source_reference', models.CharField(blank=True, max_length=160)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='curriculum.course')),
            ],
            options={
                'ordering': ['-starts_at', '-id'],
            },
        ),
    ]
