# Generated by Django 5.2.13 on 2026-05-01 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0001_initial'),
        ('accounts', '0001_initial'),
        ('curriculum', '0001_initial'),
        ('diagnostic_handoff', '0001_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessgrant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_access_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bonusaccess',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_accesses', to='resources.resource'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='curriculum.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='previewaccessgrant',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_grants', to='curriculum.course'),
        ),
        migrations.AddField(
            model_name='previewaccessgrant',
            name='diagnostic_handoff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preview_grants', to='diagnostic_handoff.diagnostichandoff'),
        ),
        migrations.AddField(
            model_name='previewaccessgrant',
            name='lead_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_grants', to='accounts.leadprofile'),
        ),
        migrations.AddField(
            model_name='previewaccessgrant',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_grants', to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='previewaccessgrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tariff',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariffs', to='curriculum.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='access_control.tariff'),
        ),
        migrations.AddField(
            model_name='bonusaccess',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_accesses', to='access_control.tariff'),
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_grants', to='access_control.tariff'),
        ),
        migrations.AddField(
            model_name='tariffentitlement',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_entitlements', to='curriculum.course'),
        ),
        migrations.AddField(
            model_name='tariffentitlement',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_entitlements', to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='tariffentitlement',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_entitlements', to='curriculum.module'),
        ),
        migrations.AddField(
            model_name='tariffentitlement',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_entitlements', to='resources.resource'),
        ),
        migrations.AddField(
            model_name='tariffentitlement',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='access_control.tariff'),
        ),
        migrations.AddIndex(
            model_name='previewaccessgrant',
            index=models.Index(fields=['user', 'status', 'expires_at'], name='access_preview_user_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='previewaccessgrant',
            constraint=models.UniqueConstraint(fields=('lead_profile', 'lesson'), name='access_preview_lead_lesson_uniq'),
        ),
        migrations.AddIndex(
            model_name='tariff',
            index=models.Index(fields=['is_active', 'sort_order'], name='access_tariff_active_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'status'], name='ac_enroll_course_stat_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='access_enrollment_user_course_uniq'),
        ),
        migrations.AddConstraint(
            model_name='bonusaccess',
            constraint=models.UniqueConstraint(fields=('tariff', 'code'), name='access_bonus_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='accessgrant',
            index=models.Index(fields=['user', 'course', 'status'], name='ac_grant_user_course_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='accessgrant',
            index=models.Index(fields=['source', 'source_reference'], name='access_grant_source_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='tariffentitlement',
            index=models.Index(fields=['entitlement_type', 'reference_key'], name='ac_ent_type_ref_idx'),
        ),
        migrations.AddConstraint(
            model_name='tariffentitlement',
            constraint=models.UniqueConstraint(fields=('tariff', 'code'), name='access_tariff_entitlement_code_uniq'),
        ),
    ]
