# Generated by Django 5.2.13 on 2026-05-01 01:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_initial'),
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='accessgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('source_reference', ''), _negated=True), fields=('source', 'source_reference'), name='access_grant_source_ref_uniq'),
        ),
    ]
