# Generated by Django 5.2.13 on 2026-05-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0003_accessgrant_access_grant_source_ref_uniq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessgrant',
            name='source',
            field=models.CharField(choices=[('payment', 'Оплата'), ('manual', 'Вручную'), ('import', 'Импорт'), ('upgrade', 'Апгрейд')], default='manual', max_length=16),
        ),
        migrations.AlterField(
            model_name='accessgrant',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('revoked', 'Отозван'), ('expired', 'Истёк'), ('frozen', 'Заморожен')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='source',
            field=models.CharField(choices=[('preview', 'Пробный доступ'), ('payment', 'Оплата'), ('manual', 'Вручную'), ('import', 'Импорт')], default='preview', max_length=16),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('preview', 'Пробный доступ'), ('active', 'Активен'), ('completed', 'Завершён'), ('canceled', 'Отменён'), ('archived', 'В архиве')], default='preview', max_length=16),
        ),
        migrations.AlterField(
            model_name='previewaccessgrant',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('consumed', 'Использован'), ('expired', 'Истёк'), ('revoked', 'Отозван')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='code',
            field=models.CharField(choices=[('workshop', 'Практикум'), ('base', 'База'), ('mentor', 'Наставник'), ('vip', 'VIP')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='tariffentitlement',
            name='entitlement_type',
            field=models.CharField(choices=[('course', 'Курс'), ('module', 'Модуль'), ('lesson', 'Урок'), ('resource', 'Материал'), ('homework_review', 'Проверка домашних заданий'), ('bonus', 'Бонус'), ('community', 'Сообщество'), ('vip_support', 'VIP поддержка')], max_length=32),
        ),
    ]
