# Generated by Django 5.2.13 on 2026-05-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0004_russian_ui_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessgrant',
            options={'ordering': ['-starts_at', '-id'], 'verbose_name': 'доступ к обучению', 'verbose_name_plural': 'доступы к обучению'},
        ),
        migrations.AlterModelOptions(
            name='bonusaccess',
            options={'ordering': ['tariff_id', 'code'], 'verbose_name': 'бонусный доступ', 'verbose_name_plural': 'бонусные доступы'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-started_at', '-id'], 'verbose_name': 'зачисление', 'verbose_name_plural': 'зачисления'},
        ),
        migrations.AlterModelOptions(
            name='previewaccessgrant',
            options={'ordering': ['-starts_at', '-id'], 'verbose_name': 'пробный доступ', 'verbose_name_plural': 'пробные доступы'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ['sort_order', 'price_amount', 'id'], 'verbose_name': 'тариф', 'verbose_name_plural': 'тарифы'},
        ),
        migrations.AlterModelOptions(
            name='tariffentitlement',
            options={'ordering': ['tariff_id', 'code'], 'verbose_name': 'право тарифа', 'verbose_name_plural': 'права тарифов'},
        ),
    ]
