# Generated by Django 5.2.13 on 2026-05-02 08:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0005_russian_admin_labels'),
        ('accounts', '0004_russian_admin_field_labels'),
        ('curriculum', '0004_russian_admin_field_labels'),
        ('diagnostic_handoff', '0004_russian_admin_field_labels'),
        ('resources', '0004_russian_admin_field_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessgrant',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='curriculum.course', verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='accessgrant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='accessgrant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_access_grants', to=settings.AUTH_USER_MODEL, verbose_name='кто выдал'),
        ),
        migrations.AlterField(
            model_name='accessgrant',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='истекает'),
        ),
        migrations.AlterField(
            model_name='accessgrant',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='метаданные'),
        ),
        migrations.AlterField(
            model_name='accessgrant',
            name='reason',
            field=models.TextField(blank=True, verbose_name='причина'),
        ),
        migrations.AlterField(
            model_name='accessgrant',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='отозвано'),
        ),
        migrations.AlterField(
            model_name='accessgrant',
            name='source',
            field=models.CharField(choices=[('payment', 'Оплата'), ('manual', 'Вручную'), ('import', 'Импорт'), ('upgrade', 'Апгрейд')], default='manual', max_length=16, verbose_name='источник'),
        ),
        migrations.AlterField(
            model_name='accessgrant',
            name='source_reference',
            field=models.CharField(blank=True, max_length=160, verbose_name='ссылка на источник'),
        ),
        migrations.AlterField(
            model_name='accessgrant',
            name='starts_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='начинается'),
        ),
        migrations.AlterField(
            model_name='accessgrant',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('revoked', 'Отозван'), ('expired', 'Истёк'), ('frozen', 'Заморожен')], default='active', max_length=16, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='accessgrant',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_grants', to='access_control.tariff', verbose_name='тариф'),
        ),
        migrations.AlterField(
            model_name='accessgrant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='accessgrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='bonusaccess',
            name='availability_window_hours',
            field=models.PositiveIntegerField(default=48, verbose_name='окно доступности, часов'),
        ),
        migrations.AlterField(
            model_name='bonusaccess',
            name='code',
            field=models.CharField(max_length=64, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='bonusaccess',
            name='config',
            field=models.JSONField(blank=True, default=dict, verbose_name='настройки'),
        ),
        migrations.AlterField(
            model_name='bonusaccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='bonusaccess',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='bonusaccess',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_accesses', to='resources.resource', verbose_name='материал'),
        ),
        migrations.AlterField(
            model_name='bonusaccess',
            name='starts_after_purchase_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='старт после покупки, минут'),
        ),
        migrations.AlterField(
            model_name='bonusaccess',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_accesses', to='access_control.tariff', verbose_name='тариф'),
        ),
        migrations.AlterField(
            model_name='bonusaccess',
            name='title',
            field=models.CharField(max_length=160, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='bonusaccess',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='завершено'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='curriculum.course', verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='метаданные'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='source',
            field=models.CharField(choices=[('preview', 'Пробный доступ'), ('payment', 'Оплата'), ('manual', 'Вручную'), ('import', 'Импорт')], default='preview', max_length=16, verbose_name='источник'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='начато'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('preview', 'Пробный доступ'), ('active', 'Активен'), ('completed', 'Завершён'), ('canceled', 'Отменён'), ('archived', 'В архиве')], default='preview', max_length=16, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='access_control.tariff', verbose_name='тариф'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='previewaccessgrant',
            name='consumed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='использовано'),
        ),
        migrations.AlterField(
            model_name='previewaccessgrant',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_grants', to='curriculum.course', verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='previewaccessgrant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='previewaccessgrant',
            name='diagnostic_handoff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preview_grants', to='diagnostic_handoff.diagnostichandoff', verbose_name='передача из диагностики'),
        ),
        migrations.AlterField(
            model_name='previewaccessgrant',
            name='expires_at',
            field=models.DateTimeField(verbose_name='истекает'),
        ),
        migrations.AlterField(
            model_name='previewaccessgrant',
            name='lead_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_grants', to='accounts.leadprofile', verbose_name='профиль лида'),
        ),
        migrations.AlterField(
            model_name='previewaccessgrant',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_grants', to='curriculum.lesson', verbose_name='урок'),
        ),
        migrations.AlterField(
            model_name='previewaccessgrant',
            name='reason',
            field=models.TextField(blank=True, verbose_name='причина'),
        ),
        migrations.AlterField(
            model_name='previewaccessgrant',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='отозвано'),
        ),
        migrations.AlterField(
            model_name='previewaccessgrant',
            name='starts_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='начинается'),
        ),
        migrations.AlterField(
            model_name='previewaccessgrant',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('consumed', 'Использован'), ('expired', 'Истёк'), ('revoked', 'Отозван')], default='active', max_length=16, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='previewaccessgrant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='previewaccessgrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_grants', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='access_duration_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='срок доступа в днях'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='code',
            field=models.CharField(choices=[('workshop', 'Практикум'), ('base', 'База'), ('mentor', 'Наставник'), ('vip', 'VIP')], max_length=32, unique=True, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariffs', to='curriculum.course', verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='currency',
            field=models.CharField(default='RUB', max_length=3, verbose_name='валюта'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активен'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='метаданные'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='сортировка'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='title',
            field=models.CharField(max_length=160, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='tariffentitlement',
            name='code',
            field=models.CharField(max_length=64, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='tariffentitlement',
            name='config',
            field=models.JSONField(blank=True, default=dict, verbose_name='настройки'),
        ),
        migrations.AlterField(
            model_name='tariffentitlement',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_entitlements', to='curriculum.course', verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='tariffentitlement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='tariffentitlement',
            name='entitlement_type',
            field=models.CharField(choices=[('course', 'Курс'), ('module', 'Модуль'), ('lesson', 'Урок'), ('resource', 'Материал'), ('homework_review', 'Проверка домашних заданий'), ('bonus', 'Бонус'), ('community', 'Сообщество'), ('vip_support', 'VIP поддержка')], max_length=32, verbose_name='тип права'),
        ),
        migrations.AlterField(
            model_name='tariffentitlement',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_entitlements', to='curriculum.lesson', verbose_name='урок'),
        ),
        migrations.AlterField(
            model_name='tariffentitlement',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_entitlements', to='curriculum.module', verbose_name='модуль'),
        ),
        migrations.AlterField(
            model_name='tariffentitlement',
            name='reference_key',
            field=models.CharField(blank=True, max_length=160, verbose_name='ключ привязки'),
        ),
        migrations.AlterField(
            model_name='tariffentitlement',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_entitlements', to='resources.resource', verbose_name='материал'),
        ),
        migrations.AlterField(
            model_name='tariffentitlement',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='access_control.tariff', verbose_name='тариф'),
        ),
        migrations.AlterField(
            model_name='tariffentitlement',
            name='title',
            field=models.CharField(max_length=160, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='tariffentitlement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
    ]
