# Generated by Django 5.2.13 on 2026-05-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0006_russian_admin_field_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='code',
            field=models.CharField(choices=[('workshop', 'Воркшоп'), ('base', 'Базовый'), ('mentor', 'С ментором'), ('vip', 'VIP')], max_length=32, unique=True, verbose_name='код'),
        ),
    ]
