# Generated by Django 5.2.13 on 2026-04-30 23:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('prompt', models.TextField(blank=True)),
                ('publication_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('target_reference_type', models.CharField(blank=True, max_length=64)),
                ('target_reference_key', models.CharField(blank=True, max_length=140)),
                ('submission_schema', models.JSONField(blank=True, default=dict)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('max_attempts', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ('title', 'id'),
                'indexes': [models.Index(fields=['publication_status', 'due_at'], name='homework_state_due_idx'), models.Index(fields=['target_reference_type', 'target_reference_key'], name='homework_target_ref_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='homework_assignment_max_attempts_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_identifier', models.CharField(max_length=128)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('submission_state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('returned', 'Returned')], default='draft', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.homeworkassignment')),
            ],
            options={
                'ordering': ('assignment_id', 'author_identifier', '-attempt_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HomeworkReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer_identifier', models.CharField(max_length=128)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected')], max_length=24)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('rubric_snapshot', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='homework.homeworksubmission')),
            ],
            options={
                'ordering': ('-reviewed_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['assignment', 'author_identifier'], name='homework_submission_author_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['submission_state', 'submitted_at'], name='homework_submission_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='homeworksubmission',
            constraint=models.UniqueConstraint(fields=('assignment', 'author_identifier', 'attempt_number'), name='homework_submission_attempt_uniq'),
        ),
        migrations.AddConstraint(
            model_name='homeworksubmission',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gte', 1)), name='homework_submission_attempt_gte_1'),
        ),
        migrations.AddIndex(
            model_name='homeworkreview',
            index=models.Index(fields=['decision', 'reviewed_at'], name='homework_review_decision_idx'),
        ),
        migrations.AddConstraint(
            model_name='homeworkreview',
            constraint=models.UniqueConstraint(fields=('submission', 'reviewer_identifier'), name='homework_review_submission_reviewer_uniq'),
        ),
        migrations.AddConstraint(
            model_name='homeworkreview',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), models.Q(('score__gte', 0), ('score__lte', 100)), _connector='OR'), name='homework_review_score_between_0_100'),
        ),
    ]
