# Generated by Django 5.2.13 on 2026-05-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkassignment',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'В архиве')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='homeworkreview',
            name='decision',
            field=models.CharField(choices=[('approved', 'Принято'), ('changes_requested', 'Нужны правки'), ('rejected', 'Отклонено')], max_length=24),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submission_state',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено'), ('reviewed', 'Проверено'), ('returned', 'Возвращено на доработку')], default='draft', max_length=16),
        ),
    ]
