# Generated by Django 5.2.13 on 2026-05-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_russian_ui_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeworkassignment',
            options={'ordering': ('title', 'id'), 'verbose_name': 'домашнее задание', 'verbose_name_plural': 'домашние задания'},
        ),
        migrations.AlterModelOptions(
            name='homeworkreview',
            options={'ordering': ('-reviewed_at', '-id'), 'verbose_name': 'проверка домашнего задания', 'verbose_name_plural': 'проверки домашних заданий'},
        ),
        migrations.AlterModelOptions(
            name='homeworksubmission',
            options={'ordering': ('assignment_id', 'author_identifier', '-attempt_number', 'id'), 'verbose_name': 'ответ на домашнее задание', 'verbose_name_plural': 'ответы на домашние задания'},
        ),
    ]
