# Generated by Django 5.2.13 on 2026-05-02 08:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_russian_admin_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='homeworkassignment',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='срок сдачи'),
        ),
        migrations.AlterField(
            model_name='homeworkassignment',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='максимум попыток'),
        ),
        migrations.AlterField(
            model_name='homeworkassignment',
            name='opens_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='открывается'),
        ),
        migrations.AlterField(
            model_name='homeworkassignment',
            name='prompt',
            field=models.TextField(blank=True, verbose_name='задание'),
        ),
        migrations.AlterField(
            model_name='homeworkassignment',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный ID'),
        ),
        migrations.AlterField(
            model_name='homeworkassignment',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'В архиве')], default='draft', max_length=16, verbose_name='статус публикации'),
        ),
        migrations.AlterField(
            model_name='homeworkassignment',
            name='slug',
            field=models.SlugField(max_length=140, unique=True, verbose_name='URL-ярлык'),
        ),
        migrations.AlterField(
            model_name='homeworkassignment',
            name='submission_schema',
            field=models.JSONField(blank=True, default=dict, verbose_name='схема ответа'),
        ),
        migrations.AlterField(
            model_name='homeworkassignment',
            name='summary',
            field=models.TextField(blank=True, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='homeworkassignment',
            name='target_reference_key',
            field=models.CharField(blank=True, max_length=140, verbose_name='ключ привязки'),
        ),
        migrations.AlterField(
            model_name='homeworkassignment',
            name='target_reference_type',
            field=models.CharField(blank=True, max_length=64, verbose_name='тип привязки'),
        ),
        migrations.AlterField(
            model_name='homeworkassignment',
            name='title',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='homeworkassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='homeworkreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='homeworkreview',
            name='decision',
            field=models.CharField(choices=[('approved', 'Принято'), ('changes_requested', 'Нужны правки'), ('rejected', 'Отклонено')], max_length=24, verbose_name='решение'),
        ),
        migrations.AlterField(
            model_name='homeworkreview',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='обратная связь'),
        ),
        migrations.AlterField(
            model_name='homeworkreview',
            name='reviewed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='проверено'),
        ),
        migrations.AlterField(
            model_name='homeworkreview',
            name='reviewer_identifier',
            field=models.CharField(max_length=128, verbose_name='проверяющий'),
        ),
        migrations.AlterField(
            model_name='homeworkreview',
            name='rubric_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='рубрика проверки'),
        ),
        migrations.AlterField(
            model_name='homeworkreview',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='оценка'),
        ),
        migrations.AlterField(
            model_name='homeworkreview',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='homework.homeworksubmission', verbose_name='ответ'),
        ),
        migrations.AlterField(
            model_name='homeworkreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.homeworkassignment', verbose_name='домашнее задание'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='номер попытки'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='author_identifier',
            field=models.CharField(max_length=128, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='notes',
            field=models.TextField(blank=True, verbose_name='заметки'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='данные ответа'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submission_state',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено'), ('reviewed', 'Проверено'), ('returned', 'Возвращено на доработку')], default='draft', max_length=16, verbose_name='статус ответа'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='отправлено'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
    ]
