# Generated by Django 5.2.13 on 2026-04-30 23:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('asset_kind', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('document', 'Document'), ('archive', 'Archive'), ('other', 'Other')], max_length=24)),
                ('availability_status', models.CharField(choices=[('queued', 'Queued'), ('ready', 'Ready'), ('archived', 'Archived')], default='queued', max_length=16)),
                ('storage_backend', models.CharField(choices=[('local', 'Local'), ('s3', 'S3'), ('external', 'External'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('storage_key', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('mime_type', models.CharField(blank=True, max_length=127)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('title', 'id'),
                'indexes': [models.Index(fields=['availability_status', 'asset_kind'], name='media_state_kind_idx'), models.Index(fields=['storage_backend'], name='media_storage_idx')],
            },
        ),
    ]
