# Generated by Django 5.2.13 on 2026-05-01 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonMediaAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_attachments', to='curriculum.lesson')),
                ('media_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_attachments', to='media_library.mediaasset')),
            ],
            options={
                'ordering': ('lesson_id', 'media_asset_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PlaybackTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_tickets', to='media_library.lessonmediaattachment')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='lessonmediaattachment',
            constraint=models.UniqueConstraint(fields=('lesson', 'media_asset'), name='media_attach_lesson_asset_uniq'),
        ),
        migrations.AddIndex(
            model_name='playbackticket',
            index=models.Index(fields=['expires_at', 'consumed'], name='media_ticket_exp_cons_idx'),
        ),
    ]
