# Generated by Django 5.2.13 on 2026-05-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_lessonmediaattachment_playbackticket_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonmediaattachment',
            options={'ordering': ('lesson_id', 'purpose', 'position', 'id')},
        ),
        migrations.AddField(
            model_name='lessonmediaattachment',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lessonmediaattachment',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonmediaattachment',
            name='purpose',
            field=models.CharField(choices=[('primary_video', 'Primary video'), ('caption', 'Caption'), ('transcript', 'Transcript'), ('supplement', 'Supplement')], default='primary_video', max_length=32),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='availability_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('queued', 'Queued'), ('ready', 'Ready'), ('failed', 'Failed'), ('archived', 'Archived')], default='processing', max_length=16),
        ),
    ]
