# Generated by Django 5.2.13 on 2026-05-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0003_alter_lessonmediaattachment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmediaattachment',
            name='purpose',
            field=models.CharField(choices=[('primary_video', 'Основное видео'), ('caption', 'Субтитры'), ('transcript', 'Транскрипт'), ('supplement', 'Дополнительный материал')], default='primary_video', max_length=32),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='asset_kind',
            field=models.CharField(choices=[('video', 'Видео'), ('audio', 'Аудио'), ('image', 'Изображение'), ('document', 'Документ'), ('archive', 'Архив'), ('other', 'Другое')], max_length=24),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='availability_status',
            field=models.CharField(choices=[('processing', 'Обрабатывается'), ('queued', 'В очереди'), ('ready', 'Готово'), ('failed', 'Ошибка'), ('archived', 'В архиве')], default='processing', max_length=16),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='storage_backend',
            field=models.CharField(choices=[('local', 'Локальное хранилище'), ('s3', 'S3'), ('external', 'Внешний сервис'), ('unknown', 'Не указано')], default='unknown', max_length=16),
        ),
    ]
