# Generated by Django 5.2.13 on 2026-05-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0004_russian_ui_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonmediaattachment',
            options={'ordering': ('lesson_id', 'purpose', 'position', 'id'), 'verbose_name': 'медиа в уроке', 'verbose_name_plural': 'медиа в уроках'},
        ),
        migrations.AlterModelOptions(
            name='mediaasset',
            options={'ordering': ('title', 'id'), 'verbose_name': 'медиафайл', 'verbose_name_plural': 'медиафайлы'},
        ),
        migrations.AlterModelOptions(
            name='playbackticket',
            options={'ordering': ('-created_at', '-id'), 'verbose_name': 'билет воспроизведения', 'verbose_name_plural': 'билеты воспроизведения'},
        ),
    ]
