# Generated by Django 5.2.13 on 2026-05-02 08:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_russian_admin_field_labels'),
        ('media_library', '0005_russian_admin_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmediaattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='lessonmediaattachment',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='обязательное'),
        ),
        migrations.AlterField(
            model_name='lessonmediaattachment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_attachments', to='curriculum.lesson', verbose_name='урок'),
        ),
        migrations.AlterField(
            model_name='lessonmediaattachment',
            name='media_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_attachments', to='media_library.mediaasset', verbose_name='медиафайл'),
        ),
        migrations.AlterField(
            model_name='lessonmediaattachment',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='позиция'),
        ),
        migrations.AlterField(
            model_name='lessonmediaattachment',
            name='purpose',
            field=models.CharField(choices=[('primary_video', 'Основное видео'), ('caption', 'Субтитры'), ('transcript', 'Транскрипт'), ('supplement', 'Дополнительный материал')], default='primary_video', max_length=32, verbose_name='назначение'),
        ),
        migrations.AlterField(
            model_name='lessonmediaattachment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='asset_kind',
            field=models.CharField(choices=[('video', 'Видео'), ('audio', 'Аудио'), ('image', 'Изображение'), ('document', 'Документ'), ('archive', 'Архив'), ('other', 'Другое')], max_length=24, verbose_name='тип медиа'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='availability_status',
            field=models.CharField(choices=[('processing', 'Обрабатывается'), ('queued', 'В очереди'), ('ready', 'Готово'), ('failed', 'Ошибка'), ('archived', 'В архиве')], default='processing', max_length=16, verbose_name='статус доступности'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='checksum_sha256',
            field=models.CharField(blank=True, max_length=64, verbose_name='SHA-256'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='длительность, секунд'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file_size_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='размер файла, байт'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='метаданные'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='mime_type',
            field=models.CharField(blank=True, max_length=127, verbose_name='MIME-тип'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный ID'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='slug',
            field=models.SlugField(max_length=140, unique=True, verbose_name='URL-ярлык'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='ссылка на источник'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='storage_backend',
            field=models.CharField(choices=[('local', 'Локальное хранилище'), ('s3', 'S3'), ('external', 'Внешний сервис'), ('unknown', 'Не указано')], default='unknown', max_length=16, verbose_name='хранилище'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='storage_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='ключ в хранилище'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='title',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='playbackticket',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_tickets', to='media_library.lessonmediaattachment', verbose_name='медиа в уроке'),
        ),
        migrations.AlterField(
            model_name='playbackticket',
            name='consumed',
            field=models.BooleanField(default=False, verbose_name='использован'),
        ),
        migrations.AlterField(
            model_name='playbackticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='playbackticket',
            name='expires_at',
            field=models.DateTimeField(verbose_name='истекает'),
        ),
        migrations.AlterField(
            model_name='playbackticket',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='метаданные'),
        ),
        migrations.AlterField(
            model_name='playbackticket',
            name='token_hash',
            field=models.CharField(max_length=128, unique=True, verbose_name='хэш токена'),
        ),
        migrations.AlterField(
            model_name='playbackticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
    ]
