# Generated by Django 5.2.13 on 2026-05-01 00:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email'), ('system', 'System')], max_length=16)),
                ('template_key', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_at', 'id'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='notify_job_status_schedule_idx'), models.Index(fields=['channel', 'template_key'], name='notify_job_channel_tpl_idx')],
            },
        ),
    ]
