# Generated by Django 5.2.13 on 2026-05-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationjob",
            name="dedupe_key",
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name="notificationjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("dead_letter", "Dead letter"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(dedupe_key__isnull=False),
                fields=("dedupe_key",),
                name="notify_job_dedupe_key_uniq",
            ),
        ),
    ]
