# Generated by Django 5.2.13 on 2026-05-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationjob_dedupe_key_dead_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationjob',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email'), ('system', 'Система')], max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('dead_letter', 'Не доставлено'), ('canceled', 'Отменено')], default='pending', max_length=16),
        ),
    ]
