# Generated by Django 5.2.13 on 2026-05-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_russian_ui_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationjob',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Почта'), ('system', 'Система')], max_length=16),
        ),
    ]
