# Generated by Django 5.2.13 on 2026-05-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_russian_email_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationjob',
            options={'ordering': ['scheduled_at', 'id'], 'verbose_name': 'уведомление', 'verbose_name_plural': 'уведомления'},
        ),
    ]
