# Generated by Django 5.2.13 on 2026-05-02 08:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_russian_admin_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationjob',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='попытки'),
        ),
        migrations.AlterField(
            model_name='notificationjob',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Почта'), ('system', 'Система')], max_length=16, verbose_name='канал'),
        ),
        migrations.AlterField(
            model_name='notificationjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='notificationjob',
            name='dedupe_key',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='ключ идемпотентности'),
        ),
        migrations.AlterField(
            model_name='notificationjob',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='последняя ошибка'),
        ),
        migrations.AlterField(
            model_name='notificationjob',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='данные'),
        ),
        migrations.AlterField(
            model_name='notificationjob',
            name='scheduled_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='запланировано'),
        ),
        migrations.AlterField(
            model_name='notificationjob',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='отправлено'),
        ),
        migrations.AlterField(
            model_name='notificationjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('dead_letter', 'Не доставлено'), ('canceled', 'Отменено')], default='pending', max_length=16, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='notificationjob',
            name='template_key',
            field=models.CharField(max_length=100, verbose_name='ключ шаблона'),
        ),
        migrations.AlterField(
            model_name='notificationjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='notificationjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_jobs', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
